# Generated by Django 3.1.3 on 2020-11-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201116_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='updatedtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
