# Generated by Django 3.1.3 on 2020-11-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_club_updatedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='updatedtime',
            field=models.TimeField(auto_now=True),
        ),
    ]
