# Generated by Django 3.1.3 on 2020-11-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201123_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='updatedtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
