# Generated by Django 3.1.1 on 2020-11-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201124_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('images1', models.ImageField(default='', upload_to='clients/images')),
                ('images2', models.ImageField(default='', upload_to='clients/images')),
                ('images3', models.ImageField(default='', upload_to='clients/images')),
            ],
        ),
    ]
