# Generated by Django 3.1.3 on 2020-11-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venture', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('issue', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='image1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='club',
            name='image2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='club',
            name='image3',
            field=models.URLField(blank=True),
        ),
    ]
