# Generated by Django 3.1.3 on 2020-11-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_club_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='username',
        ),
    ]
